name: Build and Release EXE

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

permissions:
  contents: write

jobs:
  build:
    name: Build EXE on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile main.py
        shell: cmd

      - name: Archive EXE
        uses: actions/upload-artifact@v3
        with:
          name: compiled-exe
          path: dist/main.exe


  create_tags:
    name : Create a tag
    runs-on: ubuntu-latest
    steps:
      - name : Checkout repository
        uses : actions/checkout@v3
      - name : Create new tag
        run: |
          git tag v1.0.${{github.run_number}}
          git push origin --tags


  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download EXE from build job
        uses: actions/download-artifact@v3
        with:
          name: compiled-exe
          path: ./dist

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/lunch.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref }}

   
